---

- name: Set 'look and feel' to Breeze theme
  command:
    cmd: lookandfeeltool --apply org.kde.breeze.desktop
  tags:
    - kde_settings

- name: Make double-click the default
  command:
    cmd: kwriteconfig5 --file kdeglobals --group "KDE" --key "SingleClick" "false"
  tags:
    - kde_settings

- name: Make caps lock a control key
  command:
    cmd: kwriteconfig5 --file kxkbrc --group "Layout" --key "Options" "ctrl:nocaps"
  tags:
    - kde_settings

- name: Apply shared dotfiles
  copy:
    src: assets/kde/
    dest: "{{ ansible_env.HOME }}/.config/"
    mode: 0600
  tags:
    - kde_settings
