version: '3'

services:
  giteadb:
    container_name: giteadb
    environment:
      - MARIADB_ROOT_PASSWORD=84ZfXMBuqfnVSP92
      - MARIADB_DATABASE=gitea
      - MARIADB_USER=gitea
      - MARIADB_PASSWORD=ssb2TLJnyJ4FHExL
    hostname: giteadb
    networks:
      - gitea
    image: mariadb/server:10.3
    restart: always
    volumes:
      - /nas0/db/gitea:/var/lib/mysql

  gitea:
    container_name: gitea
    depends_on:
      - giteadb
    image: gitea/gitea:1.11
    hostname: gitea
    environment:
      - USER_UID=10100
      - USER_GID=10100
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=http"
      - "traefik.http.routers.gitea.rule=Host(`gitea.francopuccini.casa`)"
      - "traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gitea.middlewares=gitea-https-redirect"
      - "traefik.http.routers.gitea-secure.entrypoints=https"
      - "traefik.http.routers.gitea-secure.rule=Host(`gitea.francopuccini.casa`)"
      - "traefik.http.routers.gitea-secure.tls=true"
      - "traefik.http.routers.gitea-secure.tls.certresolver=http"
      - "traefik.http.routers.gitea-secure.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - gitea
    ports:
      - "3000:3000"
      - "322:22"
    restart: always
    volumes:
      - /nas0/appdata/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  proxy:
    external: true
  gitea:
    external: true
