version: '3'

services:
  airsonic:
    container_name: airsonic
    image: airsonic/airsonic
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.entrypoints=http"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.francopuccini.casa`)"
      - "traefik.http.middlewares.airsonic-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.airsonic.middlewares=airsonic-https-redirect"
      - "traefik.http.routers.airsonic-secure.entrypoints=https"
      - "traefik.http.routers.airsonic-secure.rule=Host(`airsonic.francopuccini.casa`)"
      - "traefik.http.routers.airsonic-secure.tls=true"
      - "traefik.http.routers.airsonic-secure.tls.certresolver=http"
      - "traefik.http.routers.airsonic-secure.service=airsonic"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    ports:
      - "4040:4040"
    restart: unless-stopped
    volumes:
      - /nas0/userdata/media/playlists:/airsonic/playlists
      - /nas0/userdata/media/music:/airsonic/music

networks:
  proxy:
    external: true