version: '3'

services:
  dokuwiki:
    container_name: dokuwiki
    environment:
      - TZ=America/New_York
      - DOKUWIKI_USERNAME=admin
      - DOKUWIKI_PASSWORD=XNufdS6hdxWbgJmOeICV
      - DOKUWIKI_FULL_NAME=Admin
      - DOKUWIKI_EMAIL=bradfrank@fastmail.com
      - DOKUWIKI_WIKI_NAME=Brad's Wiki
    image: bitnami/dokuwiki:0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dokuwiki.entrypoints=http"
      - "traefik.http.routers.dokuwiki.rule=Host(`dokuwiki.francopuccini.casa`)"
      - "traefik.http.middlewares.dokuwiki-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dokuwiki.middlewares=dokuwiki-https-redirect"
      - "traefik.http.routers.dokuwiki-secure.entrypoints=https"
      - "traefik.http.routers.dokuwiki-secure.rule=Host(`dokuwiki.francopuccini.casa`)"
      - "traefik.http.routers.dokuwiki-secure.tls=true"
      - "traefik.http.routers.dokuwiki-secure.tls.certresolver=http"
      - "traefik.http.routers.dokuwiki-secure.service=dokuwiki"
      - "traefik.http.services.dokuwiki.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    ports:
      - 8020:80
    restart: always
    volumes:
      - /nas0/appdata/dokuwiki:/bitnami
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  proxy:
    external: true