---

- name: Create ~/Projects folder
  file:
    path: "{{ homedir }}/Projects"
    state: directory
    mode: '0750'

- name: Create ~/Development symlink to ~/Projects
  file:
    src: "{{ homedir }}/Projects"
    dest: "{{ homedir }}/Development"
    state: link

- name: Create ~/Scratch folder
  file:
    path: "{{ homedir }}/Projects"
    state: directory
    mode: '0750'

- name: Ensure ~/.ssh directory exists
  file:
    path: "{{ homedir }}/.ssh"
    state: directory
    mode: 0700

- name: Install GitHub deploy key
  copy:
    src: assets/github
    dest: "{{ homedir }}/.ssh/deploy_key"
    mode: 0600

- name: Clone projects
  git:
    repo: "git@github.com:bradleyfrank/{{ item }}.git"
    dest: "{{ homedir }}/Projects/{{ item }}"
    key_file: "{{ homedir }}/.ssh/deploy_key"
    version: master
    track_submodules: True
    accept_hostkey: True
  with_items: "{{ my_git_projects }}"

- name: Remove GitHub deploy key
  file:
    path: "{{ homedir }}/.ssh/deploy_key"
    state: absent

- name: Install VSCode extensions
  command:
    cmd: "/usr/bin/codium --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"

- name: Install Python packages
  pip:
    name: "{{ python_packages }}"
    extra_args: --user