---

- name: Create ~/.ssh directory
  file:
    path: "{{ homedir }}/.ssh"
    state: directory
    mode: '0700'

- name: Clone dotfiles repo
  git:
    repo: "https://github.com/bradleyfrank/dotfiles.git"
    dest: "{{ homedir }}/.dotfiles"
    version: master
    force: True
    track_submodules: True
    accept_hostkey: True

- name: Ignore executable bit changes in dotfiles repo
  git_config:
    name: core.fileMode
    repo: "{{ homedir }}/.dotfiles"
    scope: local
    value: "false"

- name: Create post-merge script in dotfiles repo
  copy:
    content: |
      chmod 700 ./ssh
      chmod 700 ./ssh/.ssh
      chmod 600 ./ssh/.ssh/authorized_keys
      chmod 600 ./ssh/.ssh/config
      chmod 775 ./bin/.local/bin/*
    dest: "{{ homedir }}/.dotfiles/.git/hooks/post-merge"
    mode: '0750'

- name: Apply Git post-merge script
  command:
    cmd: "pushd {{ homedir }}/.dotfiles ; ./.git/hooks/post-merge ; popd"

- name: Stow dotfiles
  command:
    cmd: "{{ homedir }}/.dotfiles/bin/.local/bin/stow-dotfiles -b"