---

- name: Get desktop environment
  set_fact:
    desktop: "{{ lookup('env','XDG_CURRENT_DESKTOP')|lower }}"

- name: Load desktop environment variables
  include_vars: "{{ desktop }}.yml"

- include_tasks: repos.yml

- name: Install packages
  become: yes
  package:
    name: "{{ packages }} + {{ de_packages }}"
    state: present

- include_tasks: dconf.yml